name: xylophone_cat
description: A new Flutter project.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  assets_audio_player: ^3.0.5
  audioplayers: ^0.20.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true


  assets:
    - assets/images/cat.jpg
    - assets/note1.wav
    - assets/note2.wav
    - assets/note3.wav
    - assets/note4.wav
    - assets/note5.wav
    - assets/note6.wav
    - assets/note7.wav
    - assets/images/catt.jpg